apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jbrw
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jbrw
    app.kubernetes.io/part-of: byoc-app-abkm
  name: jbrw
spec:
  rules:
  - host: jbrw-byoc-uhqi-tenant.apps.4ff0dce2eb8c9960fbb4.hypershift.aws-2.ci.openshift.org
    http:
      paths:
      - backend:
          service:
            name: jbrw
            port:
              number: 8081
        path: /
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
